app:
  app_name: “lottery_wechat"
  version: ”v0.0.1"
  port: 8080
  run_mode: release

log:
  log_pattern: "file"
  log_path: "./log/server.log"
  save_days: 1
  level: "info"

db:
  host: "localhost"
  port: 3306
  user: "root"
  password: "root"
  dbname: "lottery_system"
  max_idle_conns: 5
  max_open_conns: 20
  max_lifetime: 300